// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB69ELzb7fP0CslaSf4mVnAydC_2pITQuc',
    appId: '1:1036113362614:web:f48fd0d898878b2c83b017',
    messagingSenderId: '1036113362614',
    projectId: 'mess-management-250df',
    authDomain: 'mess-management-250df.firebaseapp.com',
    storageBucket: 'mess-management-250df.firebasestorage.app',
    measurementId: 'G-RB8617VMS1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo8wm0iTfAhqLT-zmtSNk9rIkHJtj_Z5s',
    appId: '1:1036113362614:android:f4802b93a6cbe1b883b017',
    messagingSenderId: '1036113362614',
    projectId: 'mess-management-250df',
    storageBucket: 'mess-management-250df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKtxH3O9MBCwuW4ucUDyi4Zo2gEUrgV-E',
    appId: '1:1036113362614:ios:c6e866bf2d6713ca83b017',
    messagingSenderId: '1036113362614',
    projectId: 'mess-management-250df',
    storageBucket: 'mess-management-250df.firebasestorage.app',
    iosBundleId: 'com.example.messManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKtxH3O9MBCwuW4ucUDyi4Zo2gEUrgV-E',
    appId: '1:1036113362614:ios:c6e866bf2d6713ca83b017',
    messagingSenderId: '1036113362614',
    projectId: 'mess-management-250df',
    storageBucket: 'mess-management-250df.firebasestorage.app',
    iosBundleId: 'com.example.messManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB69ELzb7fP0CslaSf4mVnAydC_2pITQuc',
    appId: '1:1036113362614:web:6360c856405d511d83b017',
    messagingSenderId: '1036113362614',
    projectId: 'mess-management-250df',
    authDomain: 'mess-management-250df.firebaseapp.com',
    storageBucket: 'mess-management-250df.firebasestorage.app',
    measurementId: 'G-RG0SR010G7',
  );

}